apiVersion: v1
kind: Service
metadata:
  name: go-app-service
spec:
  selector:
    app: go-app
  ports:
    - protocol: TCP
      port: 80 # External port for your app
      targetPort: 8080 # The container's port
  type: LoadBalancer # Creates a Google Cloud Load Balancer to expose your app to the internet