apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
type: Opaque
data:
  # echo -n 'your-strong-password' | base64
  POSTGRES_PASSWORD: cG9zdGdyZXM=
  # You can also add POSTGRES_USER and POSTGRES_DB if you don't want to use defaults
  POSTGRES_USER: cG9zdGdyZXM= # default is 'postgres'
  POSTGRES_DB: cmVzdWx0X2Ri # default is 'postgres' or username